---
# rule level : off or 0 , warn or 1 , error or 2

extends:
  - plugin:vue/essential
  - eslint:recommended
  - google

env:
  es6: true

rules:
  max-len:
    - warn
    - code: 250

  no-console: 0

  linebreak-style: 0


parserOptions:
  parser: babel-eslint
  allowImportExportEverywhere: false

