---

extends:
  - plugin:vue/essential
  - eslint:recommended
  - google

env:
  es6: true

rules:
  max-len:
    - warn
    - code: 250

  no-console: 0

#  no-irregular-whitespace: 0

parserOptions:
  parser: babel-eslint
  allowImportExportEverywhere: false

